// STEP 4: 홍보 주제 DB (AI 사용 없음, 고정 데이터)
// 각 주제는 countryInterests.js의 관심사 문자열과 매칭되는 tags를 가진다.
// (한국어권 국가는 한국어 tag로, 영어권(English)은 영어 tag로 매칭된다)
// titleEn은 English(영어권) 대상일 때 화면에 표시된다.

export const TOPICS = [
  { id: 'first-korean', titleKo: '처음 배우는 한국어', titleEn: 'First Steps in Korean', tags: ['기초 한국어', 'Korean for beginners'] },
  { id: 'sentence-of-day', titleKo: '오늘의 한국어 한 문장', titleEn: 'Korean Sentence of the Day', tags: ['기초 한국어', 'Korean for beginners', '실생활 한국어'] },
  { id: 'travel-expression', titleKo: '한국 여행 필수 표현', titleEn: 'Essential Korean Travel Phrases', tags: ['한국 여행', 'Korean travel phrases'] },
  { id: 'restaurant-order', titleKo: '한국 식당에서 주문하기', titleEn: 'Ordering at a Korean Restaurant', tags: ['한국 음식', 'Korean food', '실생활 한국어'] },
  { id: 'cafe-order', titleKo: '한국 카페에서 주문하기', titleEn: 'Ordering at a Korean Cafe', tags: ['한국 카페', 'Korean cafe phrases'] },
  { id: 'convenience-store', titleKo: '한국 편의점에서 사용하는 표현', titleEn: 'Phrases for Korean Convenience Stores', tags: ['실생활 한국어', 'Useful Korean expressions', '쇼핑'] },
  { id: 'shopping-korea', titleKo: '한국에서 쇼핑하기', titleEn: 'Shopping in Korea', tags: ['쇼핑', '한국 여행'] },
  { id: 'asking-directions', titleKo: '한국에서 길 묻기', titleEn: 'Asking for Directions in Korea', tags: ['한국 여행', 'Korean travel phrases', '실생활 한국어'] },
  { id: 'public-transport', titleKo: '한국 대중교통 표현', titleEn: 'Korean Public Transportation Phrases', tags: ['한국 여행', 'Korean travel phrases', '실생활 한국어'] },
  { id: 'hotel-phrases', titleKo: '한국 호텔에서 사용하는 표현', titleEn: 'Phrases for Korean Hotels', tags: ['한국 여행', 'Korean travel phrases'] },
  { id: 'airport-phrases', titleKo: '한국 공항에서 사용하는 표현', titleEn: 'Phrases for Korean Airports', tags: ['한국 여행', 'Korean travel phrases'] },
  { id: 'common-expressions', titleKo: '한국 사람이 자주 쓰는 표현', titleEn: 'Common Expressions Koreans Use', tags: ['실생활 한국어', 'Useful Korean expressions'] },
  { id: 'basic-hangul', titleKo: '기초 한글 배우기', titleEn: 'Learning Basic Hangul', tags: ['기초 한국어', 'Learn Hangul'] },
  { id: 'reading-hangul', titleKo: '한글 읽기', titleEn: 'Reading Hangul', tags: ['기초 한국어', 'Learn Hangul'] },
  { id: 'pronunciation', titleKo: '한국어 발음 연습', titleEn: 'Korean Pronunciation Practice', tags: ['기초 한국어', 'Korean for beginners'] },
  { id: 'numbers', titleKo: '한국어 숫자', titleEn: 'Korean Numbers', tags: ['기초 한국어', 'Korean for beginners'] },
  { id: 'time-expression', titleKo: '한국어 시간 표현', titleEn: 'Telling Time in Korean', tags: ['기초 한국어', 'Korean for beginners', '실생활 한국어'] },
  { id: 'date-expression', titleKo: '한국어 날짜 표현', titleEn: 'Korean Date Expressions', tags: ['기초 한국어', 'Korean for beginners'] },
  { id: 'greetings', titleKo: '한국어 인사', titleEn: 'Korean Greetings', tags: ['기초 한국어', 'Korean for beginners'] },
  { id: 'self-introduction', titleKo: '한국어 자기소개', titleEn: 'Self-Introduction in Korean', tags: ['기초 한국어', 'Korean for beginners'] },
  { id: 'thank-you', titleKo: '감사할 때 사용하는 한국어', titleEn: 'Saying Thank You in Korean', tags: ['실생활 한국어', 'Useful Korean expressions'] },
  { id: 'apology', titleKo: '사과할 때 사용하는 한국어', titleEn: 'Apologizing in Korean', tags: ['실생활 한국어', 'Useful Korean expressions'] },
  { id: 'friend-expressions', titleKo: '친구와 사용하는 표현', titleEn: 'Expressions to Use with Friends', tags: ['실생활 한국어', 'Useful Korean expressions'] },
  { id: 'school-expressions', titleKo: '한국 학교에서 사용하는 표현', titleEn: 'Phrases for Korean School Life', tags: ['한국 학교', '실생활 한국어'] },
  { id: 'workplace-expressions', titleKo: '한국 직장에서 사용하는 표현', titleEn: 'Phrases for Korean Workplace', tags: ['한국 취업', '실생활 한국어'] },
  { id: 'life-expression', titleKo: '한국 생활 필수 표현', titleEn: 'Essential Korean Daily Life Phrases', tags: ['한국 생활', '실생활 한국어', 'Useful Korean expressions'] },
  { id: 'food-names', titleKo: '한국 음식 이름 배우기', titleEn: 'Learning Korean Food Names', tags: ['한국 음식', 'Korean food'] },
  { id: 'kpop-expression', titleKo: 'K-POP에서 자주 듣는 한국어', titleEn: 'Korean Words You Hear in K-pop', tags: ['K-POP', 'K-pop Korean', 'K-콘텐츠'] },
  { id: 'kdrama-expression', titleKo: 'K-드라마에서 자주 듣는 표현', titleEn: 'Expressions You Hear in K-dramas', tags: ['K-드라마', 'K-drama Korean', 'K-콘텐츠'] },
  { id: 'beginner-mistakes', titleKo: '초보자가 자주 틀리는 한국어', titleEn: 'Common Mistakes Beginners Make', tags: ['기초 한국어', 'Korean for beginners'] },
  { id: 'before-travel', titleKo: '한국 여행 전에 알아둘 표현', titleEn: 'Phrases to Know Before Traveling to Korea', tags: ['한국 여행', 'Korean travel phrases'] },
  { id: 'cafe-menu', titleKo: '한국 카페 메뉴 읽기', titleEn: 'Reading a Korean Cafe Menu', tags: ['한국 카페', 'Korean cafe phrases'] },
  { id: 'restaurant-menu', titleKo: '한국 음식점 메뉴 읽기', titleEn: 'Reading a Korean Restaurant Menu', tags: ['한국 음식', 'Korean food'] },
  { id: 'asking-price', titleKo: '한국에서 가격 묻기', titleEn: 'Asking Prices in Korea', tags: ['쇼핑', '실생활 한국어', '한국 여행'] },
  { id: 'asking-help', titleKo: '한국에서 도움 요청하기', titleEn: 'Asking for Help in Korea', tags: ['실생활 한국어', 'Useful Korean expressions', '한국 생활'] },
  { id: 'use-today', titleKo: '오늘 바로 사용할 수 있는 한국어', titleEn: 'Korean You Can Use Today', tags: ['실생활 한국어', 'Useful Korean expressions'] },
  { id: 'short-replies', titleKo: '한국인이 자주 하는 짧은 대답', titleEn: 'Short Replies Koreans Often Use', tags: ['실생활 한국어', 'Useful Korean expressions'] },
  { id: 'honorifics-basic', titleKo: '존댓말 기초', titleEn: 'Basics of Korean Honorifics', tags: ['기초 한국어', 'Korean for beginners', '한국 문화', 'Korean culture'] },
  { id: 'formal-vs-casual', titleKo: '반말과 존댓말 차이', titleEn: 'Formal vs. Informal Korean', tags: ['기초 한국어', '한국 문화', 'Korean culture'] },
  { id: 'free-learning', titleKo: '무료 한국어 학습 추천', titleEn: 'Free Korean Learning Resources', tags: ['한국어 학습', 'Free Korean learning'] },
  { id: 'busan-travel', titleKo: '부산 여행 필수 표현', titleEn: 'Essential Phrases for Traveling to Busan', tags: ['부산 여행', '한국 여행', 'Korean travel phrases'] },
  { id: 'study-abroad-prep', titleKo: '한국 유학 준비하기', titleEn: 'Preparing to Study in Korea', tags: ['한국 유학', '한국 생활'] },
  { id: 'university-life', titleKo: '한국 대학 생활 표현', titleEn: 'Expressions for Korean University Life', tags: ['한국 유학', '한국 학교'] },
  { id: 'kcontent-expression', titleKo: '한국 콘텐츠 속 한국어 표현', titleEn: 'Korean Expressions in K-content', tags: ['K-콘텐츠', 'K-POP', 'K-드라마', 'Korean culture'] },
  { id: 'name-in-hangul', titleKo: '한글로 이름 쓰기', titleEn: 'Writing Your Name in Hangul', tags: ['기초 한국어', 'Learn Hangul'] },
];
